# Generated by Django 5.1.1 on 2024-09-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_courses_courseyear_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='courseType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.courses'),
        ),
    ]
